name: cryptoville
description: A gamified defi world to bring millions of people to world of web3

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web3: ^2.1.6
  provider: ^6.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/characters/
    - assets/images/characters/hero/
    - assets/images/maps/


